name: YouTube Live Catcher
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/3 * * *'
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checar Repositório
        uses: actions/checkout@v2
        run: |
           chmod +x ytblive_catcher.sh
           ./ytblive_catcher.sh
        shell: bash
      - name: Commit report
        run: |
          git config --global user.email "lcdevilarte@hotmail.com"
          git config --global user.name "Luiz Carlos Devilarte"
          git add -A
          git commit -m "Canais Atualizados!"
          git push